settings:
  reward: ${reward}
  difficulty: ${difficulty}
  show_gui: ${show_gui}
  dt: &dt ${dt}
  max_episode_steps: &steps 300
  action_frequency: 30
  simulation_frequency: 240
observation:
  with_tactile_sensor: ${with_tactile_sensor}
  with_force: ${with_force}
  with_gripper_width: &gripper_width False
  relative: &relative True
  with_noise: ${with_noise}
action:
  with_gripper_width: *gripper_width
objects:
  table:
    urdf_path: "table/table.urdf"
    base_position: [0.5, 0, -0.6]
  board:
    urdf_path: "data/peg_in_hole_board/peg_in_hole_board.urdf"
  cylinder:
    urdf_path: "data/cylinder/cylinder.urdf"
  hexagonal_prism:
    urdf_path: "data/hexagonal_prism/hexagonal_prism.urdf"
  square_prism:
    urdf_path: "data/square_prism/square_prism.urdf"
tacto:
  width: 64
  height: 64
  visualize_gui: ${visualize_tacto}
sawyer_gripper:
  robot_params:
    urdf_path: "robots/sawyer_wsg50.urdf"
    use_fixed_base: True
  init_state:
    end_effector:
      position: [0.35, 0, 0.40]
      orientation: [-0.7071, 0.7071, 0, 0]
    gripper_width: 0.080
pybullet_camera:
  cameraDistance: 0.6
  cameraYaw: 15.
  cameraPitch: -20.
  cameraTargetPosition: [0.5, 0, 0.08]